### ISSUE TITLE
How to use a next and a previous button instead of a swipe?

### ISSUE THREAD

**Issue by jibaud** [grihlo/stacked_card_carousel#2]

**Comment by grihlo** [comment]
I don't understand exactly what do you mean with next and previous buttons, could you please elaborate on that? However it sound that it could be an extension for this package 🤔

**Comment by matthewrice345** [comment]
@jibaud You can pass in a PageController which will give you the ability to specify the card index with next/previous buttons.

```
    PageController controller = PageController();

    StackedCardCarousel(pageController: controller, ...)

    controller.nextPage(...)
    controller.previousPage(...)
```

**Comment by jibaud** [comment]
> @jibaud You can pass in a PageController which will give you the ability to specify the card index with next/previous buttons.
> 
> ```
>     PageController controller = PageController();
> 
>     StackedCardCarousel(pageController: controller, ...)
> 
>     controller.nextPage(...)
>     controller.previousPage(...)
> ```

Hey thank you for your answer. I was a beginner when I answered this question, now with a few more experience I realize that it was something very easy to do  😄. I'm closing the issue.
